gcloud services enable compute.googleapis.com --project $1
gcloud services enable dns.googleapis.com --project $1
gcloud projects add-iam-policy-binding $1 --member=serviceAccount:frame-customer-iaas-dev@frame-byo-development-2.iam.gserviceaccount.com --role=roles/compute.instanceAdmin
gcloud projects add-iam-policy-binding $1 --member=serviceAccount:frame-customer-iaas-dev@frame-byo-development-2.iam.gserviceaccount.com --role=roles/compute.networkAdmin
gcloud projects add-iam-policy-binding $1 --member=serviceAccount:frame-customer-iaas-dev@frame-byo-development-2.iam.gserviceaccount.com --role=roles/compute.securityAdmin
gcloud projects add-iam-policy-binding $1 --member=serviceAccount:frame-customer-iaas-dev@frame-byo-development-2.iam.gserviceaccount.com --role=roles/compute.storageAdmin
gcloud projects add-iam-policy-binding $1 --member=serviceAccount:frame-customer-iaas-dev@frame-byo-development-2.iam.gserviceaccount.com --role=roles/dns.admin
gcloud projects add-iam-policy-binding $1 --member=serviceAccount:frame-customer-iaas-dev@frame-byo-development-2.iam.gserviceaccount.com --role=roles/iam.serviceAccountUser
cd .. && rm -fR gcp-byo-cloud-shell-deployment